export const ADD_PLAYER     = 'ADD_PLAYER'
export const GET_PLAYERS    = 'GET_PLAYERS'
export const UPDATE_PLAYER  = 'UPDATE_PLAYER'
export const REMOVE_PLAYER  = 'REMOVE_PLAYER'
export const TWEET          = 'TWEET'
